version: '2'
services:
    b2share:
        build:
            context: ..
            dockerfile: dockerize/Dockerfile
        environment:
            - "B2ACCESS_CONSUMER_KEY=${B2ACCESS_CONSUMER_KEY}"
            - "B2ACCESS_SECRET_KEY=${B2ACCESS_SECRET_KEY}"
            - "USE_STAGING_B2ACCESS=${USE_STAGING_B2ACCESS}"
            - "B2SHARE_SECRET_KEY=${B2SHARE_SECRET_KEY}"
            - "B2SHARE_JSONSCHEMAS_HOST=${B2SHARE_JSONSCHEMAS_HOST}"
            - "INIT_DB_AND_INDEX=${INIT_DB_AND_INDEX}"
            - "LOAD_DEMO_COMMUNITIES_AND_RECORDS=${LOAD_DEMO_COMMUNITIES_AND_RECORDS}"
            - "B2SHARE_PREFERRED_URL_SCHEME=https"
        volumes:
            - /b2share-data:/usr/var/b2share-instance
        ports:
            - "5000:5000"
        links:
            - elasticsearch
            - redis

    elasticsearch:
        build: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"

    redis:
        image: redis:3.2
        ports:
            - "6379:6379"

    nginx:
        build: nginx
        ports:
            - "80:80"
            - "443:443"
        # volumes:
        #     - /b2share-etc/ssl:/etc/ssl/
        links:
            - b2share

    mq:
        image: rabbitmq:3.6-management
        restart: "always"
        ports:
            - "15672:15672"
            - "5672:5672"
        read_only: true
