mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_USER=b2share_evo
        - MYSQL_DATABASE=b2share_evo

elasticsearch:
    image: elasticsearch
    ports:
        - "9200:9200"
        - "9300:9300"

redis:
    image: redis
    ports:
        - "6379:6379"
